# Theme
theme: jekyll-theme-slate

# Site Settings
locale: "en-US"
title: "HT0620.GITHUB.IO"
title_separator: "-"
name: "Hyuntae Lim"
description: "Hyuntae Lim's personal website"
url: "https://ht0620.github.io"
baseurl: ""
